"""
What this file does
This is the central memory of your agent. Every node in the LangGraph pipeline reads from and writes to this state. Think of it as the "brain's short-term memory" that carries everything — conversation history, cart, plan, language, delivery info — through the entire agent lifecycle.

Why we need it
Without a typed state, LangGraph doesn't know what data flows between nodes. This gives you:

. Type safety — TypedDict catches bugs early
. Shared context — every node sees the same data
. Conversation continuity — cart and language persist across turns
"""

from typing import TypedDict, List, Optional, Any

class ShoppingState(TypedDict):
    # conversation history - full message list sent each turn
    messages: List[dict]

    # Cart items added during the session
    cart: List[dict]

    # Plan steps generated by planner node
    plan: List[str]

    # Which step we're currently on
    current_step: int

    # Detected language: "en" | "si" | "tl"
    language: str

    # Detected intent:  "search_product" | "track_order" | "checkout" etc
    intent: str

    # What info is still missing before agent can proceed
    missing_info: List[str]

    # Delivery address + date collected from user
    delivery_info: dict

    # Gift message collected from user
    gift_message: str

    # Reflector's verdict - "continue" | "replan" | "respond"
    reflection: str

    # Raw result from last MCP tool call
    last_tool_result: Any

    # Final structured JSON response sent to frontend
    response: Optional[dict]