"""
What this file does
This is the central memory of your agent. Every node in the LangGraph pipeline reads from and writes to this state. Think of it as the "brain's short-term memory" that carries everything — conversation history, cart, plan, language, delivery info — through the entire agent lifecycle.

Why we need it
Without a typed state, LangGraph doesn't know what data flows between nodes. This gives you:

. Type safety — TypedDict catches bugs early
. Shared context — every node sees the same data
. Conversation continuity — cart and language persist across turns
"""


"""
Why each field exists

messages       → full conversation history sent from frontend each turn
cart           → list of {product_id, name, price, qty} — built up during session
plan           → steps planner generates e.g. ["search", "show_cards", "ask_city"]
current_step   → which plan step we're on
language       → "en" | "si" | "tl" — detected and persisted
intent         → what user wants to do
missing_info   → what agent still needs before it can proceed
delivery_info  → {city, delivery_date} for check_delivery call
recipient      → {name, phone, address} — who receives the order
sender         → {name, phone} — who is placing the order
gift_message   → optional message to include with order
_decision      → reasoner's output — tells router what to do next
reflection     → reflector's verdict — "continue|replan|respond"
last_tool_result → raw MCP response from last tool call
response       → final structured JSON sent to frontend
"""

from typing import TypedDict, List, Optional, Any

class ShoppingState(TypedDict):
    # conversation history - full message list sent each turn
    messages: List[dict]

    # Cart items added during the session
    cart: List[dict]

    # Plan steps generated by planner node
    plan: List[str]

    # Which step we're currently on
    current_step: int

    # Detected language: "en" | "si" | "tl"
    language: str

    # Detected intent:  "search_product" | "track_order" | "checkout" etc
    intent: str

    # What info is still missing before agent can proceed or can call a tool
    missing_info: List[str]

    # Price range collected from user
    price_range: dict  # { min_price: float, max_price: float | None }

    # Temporary product cache — avoids double MCP calls
    cached_products: List[dict]

    # Selected brand filter
    selected_brand: str

    # Available brands extracted from cached products  
    available_brands: List[str]

    # Delivery address + date collected from user
    delivery_info: dict

    # Recipient info for kapruka_create_order
    recipient: dict # {name, phone}

    # Sender info for kapruka_create_order
    sender: dict # {name, phone}

    # Optional gift message for kapruka_create_order
    gift_message: str

    # Reasoner's decision - used by conditional edge router
    _decision: dict

    # Reflector's verdict - "continue" | "replan" | "respond"
    reflection: str

    # Number of failed tool attempts — prevents infinite replan loops
    retry_count: int

    # Raw result from last MCP tool call
    last_tool_result: Any

    # Final structured JSON response sent to frontend
    response: Optional[dict]